-- SE CREA LA BASE DE DATOS
CREATE DATABASE crudnodejs;
-- SE INICIALIZA LA BASE DE DATOS
use crudnodejs;
-- SE CREA LA TABLA
CREATE TABLE customer(
    id INT (6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    address VARCHAR(100) NOT NULL,
    phone VARCHAR(15)
);
-- SE MUESTRA LA TABLA
SHOW TABLES;
-- PARA DESCRIBIR LA TABLA
describe customer;

